/*
 * Log.cpp
 *
 *  Created on: Mar 15, 2014
 *      Author: dawid
 */

#include "Log.h"
#include <cassert>
#include <SLES/OpenSLES.h>

//#define SL_RESULT_SUCCESS				((SLuint32) 0x00000000)
//#define SL_RESULT_PRECONDITIONS_VIOLATED	((SLuint32) 0x00000001)
//#define SL_RESULT_PARAMETER_INVALID		((SLuint32) 0x00000002)
//#define SL_RESULT_MEMORY_FAILURE			((SLuint32) 0x00000003)
//#define SL_RESULT_RESOURCE_ERROR			((SLuint32) 0x00000004)
//#define SL_RESULT_RESOURCE_LOST			((SLuint32) 0x00000005)
//#define SL_RESULT_IO_ERROR				((SLuint32) 0x00000006)
//#define SL_RESULT_BUFFER_INSUFFICIENT		((SLuint32) 0x00000007)
//#define SL_RESULT_CONTENT_CORRUPTED		((SLuint32) 0x00000008)
//#define SL_RESULT_CONTENT_UNSUPPORTED		((SLuint32) 0x00000009)
//#define SL_RESULT_CONTENT_NOT_FOUND		((SLuint32) 0x0000000A)
//#define SL_RESULT_PERMISSION_DENIED		((SLuint32) 0x0000000B)
//#define SL_RESULT_FEATURE_UNSUPPORTED		((SLuint32) 0x0000000C)
//#define SL_RESULT_INTERNAL_ERROR			((SLuint32) 0x0000000D)
//#define SL_RESULT_UNKNOWN_ERROR			((SLuint32) 0x0000000E)
//#define SL_RESULT_OPERATION_ABORTED		((SLuint32) 0x0000000F)
//#define SL_RESULT_CONTROL_LOST			((SLuint32) 0x00000010)
const char* errorCodes[] =
{
	"SL_RESULT_SUCCESS",
	"SL_RESULT_PRECONDITIONS_VIOLATED",
	"SL_RESULT_PARAMETER_INVALID",
	"SL_RESULT_MEMORY_FAILURE",
	"SL_RESULT_RESOURCE_ERROR",
	"SL_RESULT_RESOURCE_LOST",
	"SL_RESULT_IO_ERROR",
	"SL_RESULT_BUFFER_INSUFFICIENT",
	"SL_RESULT_CONTENT_CORRUPTED",
	"SL_RESULT_CONTENT_UNSUPPORTED",
	"SL_RESULT_CONTENT_NOT_FOUND",
	"SL_RESULT_PERMISSION_DENIED",
	"SL_RESULT_FEATURE_UNSUPPORTED",
	"SL_RESULT_INTERNAL_ERROR",
	"SL_RESULT_UNKNOWN_ERROR",
	"SL_RESULT_OPERATION_ABORTED",
	"SL_RESULT_CONTROL_LOST"
};


const char* getErrorMessage( int errorCode )
{
	assert( errorCode < sizeof( errorCodes ) / sizeof( *errorCodes ) );
	return errorCodes[static_cast<int> ( errorCode )];
}



